[package]
name = "aide-ed-server"
version = "0.1.0"
description = "AideEd server"
authors = ["haras-unicorn <social@haras.anonaddy.me>"]
license = "MIT"
readme = "README.md"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
aide-ed-lib = { path = "../lib" }
dioxus = { version = "0.6.3", features = ["fullstack", "liveview", "server"] }
diesel = { version = "2.2.10", features = ["postgres"] }
keycloak = "26.2.0"
reqwest = "0.12.15"
tokio = { version = "1.44.2", features = ["full"] }
axum = "0.8.4"
