[workspace]
resolver = "2"
members = ["src/*"]

[workspace.dependencies]
dioxus = { version = "0.6.3" }
aide-ed-ui = { path = "src/ui" }
aide-ed-api = { path = "src/api" }
aide-ed-lib = { path = "src/lib" }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
