[package]
name = "aide-ed-mobile"
version = "0.1.0"
description = "AideEd mobile"
authors = ["haras-unicorn <social@haras.anonaddy.me>"]
license = "MIT"
readme = "README.md"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
aide-ed-ui = { workspace = true }
aide-ed-lib = { workspace = true }

[features]
default = []
mobile = ["dioxus/mobile"]
server = ["dioxus/server"]
