[book]
authors = ["haras-unicorn <social@haras.anonaddy.me>"]
language = "en"
multilingual = false
src = "src"
title = "AideEd developer documentation"

[preprocessor.plantuml]
plantuml-cmd = "plantuml"
