[package]
name = "aide-ed-server"
version = "0.1.0"
description = "AideEd server"
authors = ["haras-unicorn <social@haras.anonaddy.me>"]
license = "MIT"
readme = "README.md"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }
aide-ed-lib = { workspace = true }
aide-ed-api = { workspace = true }
aide-ed-ui = { workspace = true }
anyhow = "1.0.98"
diesel = { version = "2.2.10", features = ["postgres"] }
keycloak = "26.2.0"
reqwest = "0.12.15"

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server", "dioxus/liveview"]
