[package]
name = "aide-ed-web"
version = "0.1.0"
description = "AideEd web"
authors = ["haras-unicorn <social@haras.anonaddy.me>"]
license = "MIT"
readme = "README.md"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
aide-ed-lib = { path = "../lib" }
dioxus = { version = "0.6.3", features = ["web"] }
