[package]
name = "aide-ed-server"
version = "0.1.0"
description = "AideEd server"
authors = ["haras-unicorn <social@haras.anonaddy.me>"]
license = "MIT"
readme = "README.md"
edition = "2021"

[dependencies]
dioxus = { workspace = true }
aide-ed-lib = { workspace = true }
aide-ed-api = { workspace = true }
aide-ed-ui = { workspace = true }
wasm-bindgen = "=0.2.100"

[features]
default = []
web = ["dioxus/web"]
server = [
  "dioxus/server",
  "dioxus/router",
  "dioxus/fullstack",
  "aide-ed-api/server",
]
